# Generated by Django 3.2 on 2022-05-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makematch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='player_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
