# Generated by Django 3.2 on 2022-05-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makematch', '0003_alter_player_drop'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avr_omw',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='omw',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='sowp',
            field=models.FloatField(default=0.0),
        ),
    ]
