# Generated by Django 3.2 on 2022-05-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makematch', '0004_auto_20220507_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rnd',
            field=models.FloatField(default=0.7501007424423416),
        ),
    ]
