# Generated by Django 3.2 on 2022-05-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makematch', '0006_auto_20220508_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rnd',
            field=models.FloatField(default=0.4814525026809283),
        ),
    ]
