# Generated by Django 3.2 on 2022-05-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makematch', '0007_alter_player_rnd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='drop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='rnd',
            field=models.FloatField(default=0.5178135239373802),
        ),
    ]
