# Generated by Django 3.2 on 2022-05-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makematch', '0009_auto_20220509_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rnd',
            field=models.FloatField(default=0.8184644604033521),
        ),
    ]
