# Generated by Django 3.2 on 2022-05-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makematch', '0011_alter_player_rnd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rnd',
            field=models.FloatField(default=0.6762383384066442),
        ),
    ]
