# Generated by Django 3.2 on 2022-05-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makematch', '0012_alter_player_rnd'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='table',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='rnd',
            field=models.FloatField(default=0.990595247472071),
        ),
    ]
