# Generated by Django 3.2 on 2022-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makematch', '0013_auto_20220511_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='walkorver_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='rnd',
            field=models.FloatField(default=0.663423350461939),
        ),
    ]
