# Generated by Django 3.2 on 2022-05-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makematch', '0015_auto_20220511_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='rnd',
            field=models.FloatField(default=0.688940871510824),
        ),
    ]
