# Generated by Django 3.2 on 2022-05-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makematch', '0016_auto_20220512_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rnd',
            field=models.FloatField(default=0.642317658045557),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player_num',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='round',
            field=models.IntegerField(default=3),
        ),
    ]
