# Generated by Django 3.2 on 2022-05-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makematch', '0017_auto_20220512_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='save_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='rnd',
            field=models.FloatField(default=0.06317198905165233),
        ),
    ]
