# Generated by Django 3.2 on 2022-05-07 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='タイトル')),
                ('round', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='所属トーナメント', to='snippets.tournament', verbose_name='大会')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('drop', models.BooleanField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='参加トーナメント', to='snippets.tournament', verbose_name='大会')),
            ],
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchpoint', models.IntegerField()),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='snippets.player', verbose_name='対戦相手')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='snippets.player', verbose_name='プレイヤー')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.round', verbose_name='ラウンド')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_A', to='snippets.player', verbose_name='プレイヤーA')),
                ('player_B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_B', to='snippets.player', verbose_name='プレイヤーB')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.round', verbose_name='ラウンド')),
            ],
        ),
    ]
