# Generated by Django 3.2 on 2022-05-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_match_matchhistory_player_round_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchhistory',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='player',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='round',
        ),
        migrations.RemoveField(
            model_name='player',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='round',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='MatchHistory',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
